name: stenography
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  file_picker: ^5.5.0
  steganograph: ^1.0.0
  get: ^4.6.5
  iconly: ^1.0.1
  lottie: ^2.6.0
  path: ^1.8.3
  encrypt: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  logger: ^2.0.2+1
  provider: ^6.0.4
  math_expressions: ^2.3.1
  google_fonts: ^6.1.0
  flutter_advanced_switch: ^3.0.1
  cryptography: ^2.7.0
  easy_localization: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/lotties/
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.ttf
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
