name: stenography
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  file_picker: ^5.5.0
  steganograph: ^1.0.0
  get: ^4.6.5
  iconly: ^1.0.1
  lottie: ^2.6.0
  path: ^1.8.3
  encrypt: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  logger: ^2.0.2+1
  provider: ^6.0.4
  math_expressions: ^2.3.1
  flutter_advanced_switch: ^3.0.1
  cryptography: ^2.7.0
  easy_localization: ^3.0.5
  share_plus: ^8.0.2
  open_filex: ^4.4.0
  rename: ^3.0.2

  flutter_inappwebview: ^6.0.0-beta.32
  flutter_downloader: ^1.11.5
  share_extend: ^2.0.0
  # charts_flutter: ^0.9.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.1  #  flutter_icons: ^1.1.0
  flutter_font_icons: ^2.2.5
  flutter_svg: ^2.0.9
  mime: ^1.0.4
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.19.0
  uuid: ^4.2.1
  collection: ^1.17.1
  # For material you.
  dynamic_color: ^1.6.8




  image: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/lotties/
    - assets/
    - assets/images/google_logo.png
    - assets/images/yahoo_logo.png
    - assets/images/bing_logo.png
    - assets/images/duckduckgo_logo.png
    - assets/images/ecosia_logo.png
    - assets/icon/icon.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.ttf
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600

